[project]
authors = ["Hamada <hamada.saleh@institutlouisbachelier.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lorenz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.89.0,<1.90"
python = ">=3.13.5,<3.14"
ipykernel = ">=6.30.1,<7"
jupyter = ">=1.1.1,<2"
ipython = ">=9.5.0,<10"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
plotly = ">=6.3.0,<7"
